version: "3.8"

services:

  fastapisel:
    container_name: fastapisel
    image: fastapisel
    build: .
    env_file:
      - .env
    environment:
      - APP_ENV=DEV
    ports:
      - '${HOST_PORT_DEV}:${APP_PORT}'
    command: "python3 main.py"
